name: Build snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |-
          sudo apt-get --yes install calibre rename

      - name: Build ebooks
        run: |-
          mkdir -p dist/markdown
          mkdir -p dist/epub
          
          # create merged markdown files
          ls -1 Saisons/ | xargs -I{} bash -c 'cat Saisons/{}/* > dist/markdown/{}.md'
          
          # create epubs
          ls -1 dist/markdown/ | xargs -I{} bash -c "ebook-convert dist/markdown/{} dist/markdown/{}.epub --max-toc-links 0 --markdown-extensions meta,toc --toc-filter '^(\[.*|GENERIQUE|Générique|FIN)'"
          rename 's/\.md//' dist/markdown/*.epub
          
          git status -sb
          git add dist
          git commit -m'chore: update dist files [skip ci]'
          git push origin HEAD


