name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |-
          sudo apt-get --yes install calibre rename

      - name: setup git config
        run: |-
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Build ebooks
        run: |-
          ./scripts/build.sh

      - name: Commit dist files
        run: |-
          git status -sb
          git add dist
          git commit -m'chore: update dist files [skip ci]'
          git push origin HEAD


